name: gh-pages auto builder
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
      - name: Install Sphinx
        run: |
          python -m pip install sphinx
          python -m pip install sphinx-rtd-theme

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - uses: actions/checkout@master
        with:
          requirements: src/requirements.txt
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: add .nojekyll
        run: |
          touch .nojekyll
      - uses: actions/checkout@master
      - name: Build and Commit
        uses: sphinx-notes/pages@v3
        with:
          documentation_path:  ./src
          requirements_path: ./requirements.txt

      - name: commit to gh-pages
        run: |
          git push origin gh-pages
          git add -f _autosummary/
          git commit -am "_autosummary"
          git push -f origin gh-pages
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages